name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Start Backend
      run: npm run start-be &
    - name: Start Frondend
      run: npm run start-fe &
    - name: Instal Playwriht Browsers
      run: npx playwright install
    - name: Start UI tests
      run: npm run test:ui

  deploy-backend:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   needs: build-tests
   steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Deploy BackEnd
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
       service_id: ${{ secrets.BACKEND_API_KEY }}
       api_key: ${{ secrets.RENDER_KEY }}
       wait_deploy: true 
       github_token: ${{ secrets.TOKEN_GITHUB }}

  deploy-frontend:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   needs: deploy-backend
   steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Deploy FrontEnd
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
       service_id: ${{ secrets.FRONTEND_API_KEY }}
       api_key: ${{ secrets.RENDER_KEY }}
       wait_deploy: true 
       github_token: ${{ secrets.TOKEN_GITHUB }}
